reload:
  messages:
    - "&bReloaded!"
    - "&5Deez nuts"
emojis:
  pog:
    - ꌵ
  rocket:
    - ꌵ

titles:
  hungry:
    Display-Title: ""
    Title: "&3&lHungry"
    Icon: ""
    Description:
      - "&r&5Line 1"
      - "&r&4Line 2"
      - "Line 3"
      - "etc"
    CustomModelData: 12
  witch:
    Title: "&3&lWitch"
    Icon: ""
    Description:
      - "&r&5Line 1"
      - "&r&4Line 2"
      - "Line 3"
    CustomModelData: 13
  player:
    Display-Title: ""
    Title: "&3뜉ꈉꈉꈉꈉꈈ&f뜏"
    Icon: ""
    Description:
      - "&r&5Default Title"
      - "&r&4Yeet"
      - "Line 3"
      - "etc"
    CustomModelData: 15

crate:
  cratetitles:
    - '&fꈉ贫'
    - '&fꈉ忿'
    - '&fꈉ鉊'
    - '&fꈉ盆'
    - '&fꈉ岔'
  cratecollect:
    - '&fꈉ贫懋洞'
    - '&fꈉ忿懋洞'
    - '&fꈉ鉊懋洞'
    - '&fꈉ盆懋洞'
    - '&fꈉ岔懋洞'



# Title Icons:
#            "솁뜖솣솊솗솑솠솢솔솓솉솦솏솋뜗솖솆솕",
#            "뜘손솤뜛뜙뜚속솄솇송솅소솃솧솘솙뜝솨",
#            "솥뜜솞솎솈솟睽瞪睁瞿睢矍瞧睑盷盹鹞睛",
#            "眠瞩眍眶瞒瞄朏鼎眦瞳ꑝ妥奚鹦胭胛爵腘",
#            "腮丹腿膪膀鄫ꑝ彤ꑝ肮肪脐胩腋胪写臆脑",
#            "臃胲膻金甑渗ꑝꑝꑝꑝꑝꑝꑝꑝꑝꑝꑝꑝ",
